'use strict';const crypto=require('node:crypto');
const SENSITIVE=new Set(['race','ethnicity','gender','disability','age_band','veteran_status']);const TRANSITIONS={registered:['validated'],validated:['analyzed'],analyzed:['qualified_review'],qualified_review:['approved','changes_requested'],changes_requested:['analyzed'],approved:['intervention_active'],intervention_active:['measured'],measured:[]};
function normalizeManifest(input){if(!input||typeof input!=='object')throw new Error('manifest required');if(!input.datasetId||!input.sourceSystem||!input.objectUri||!input.sha256)throw new Error('datasetId, sourceSystem, objectUri, and sha256 are required');if(!/^[a-f0-9]{64}$/i.test(input.sha256))throw new Error('sha256 must be hexadecimal');if(!input.lawfulPurpose||!input.retentionUntil)throw new Error('lawful purpose and retention date are required');if(!Array.isArray(input.fields)||!input.fields.length)throw new Error('field inventory required');if(input.fields.some((field)=>field.toLowerCase().includes('name')||field.toLowerCase().includes('email')))throw new Error('direct identifiers are not accepted in analytics manifests');return{datasetId:String(input.datasetId),sourceSystem:String(input.sourceSystem),objectUri:String(input.objectUri),sha256:input.sha256.toLowerCase(),lawfulPurpose:String(input.lawfulPurpose),retentionUntil:new Date(input.retentionUntil).toISOString(),fields:[...new Set(input.fields.map(String))].sort()};}
function validateMetricDefinition(definition){if(!definition||!definition.metricId||!definition.numerator||!definition.denominator)throw new Error('metricId, numerator, and denominator are required');const minCohort=Number(definition.minCohort);if(!Number.isInteger(minCohort)||minCohort<10)throw new Error('minCohort must be an integer of at least 10');const cohorts=definition.cohorts||[];if(!cohorts.length||cohorts.some((field)=>!SENSITIVE.has(field)))throw new Error('cohorts must use approved sensitive-attribute categories');if(!definition.version||!definition.owner||!definition.validFrom)throw new Error('version, owner, and validFrom are required');return{...definition,minCohort,cohorts:[...new Set(cohorts)].sort()};}
function suppressSmallCohorts(rows,minCohort){return rows.map((row)=>Number(row.count)<minCohort?{cohort:row.cohort,suppressed:true,count:null,value:null}:{...row,suppressed:false});}
function wilsonInterval(successes,total,z=1.96){if(!Number.isInteger(successes)||!Number.isInteger(total)||total<=0||successes<0||successes>total)throw new Error('valid integer counts required');const p=successes/total;const denominator=1+z*z/total;const center=(p+z*z/(2*total))/denominator;const margin=z*Math.sqrt((p*(1-p)+z*z/(4*total))/total)/denominator;return{estimate:p,low:Math.max(0,center-margin),high:Math.min(1,center+margin),n:total};}
function analysisHash(input){return crypto.createHash('sha256').update(JSON.stringify(input)).digest('hex');}
function assertTransition(from,to,role,context={}){if(!(TRANSITIONS[from]||[]).includes(to))throw new Error(`invalid transition: ${from} -> ${to}`);if(to==='validated'&&(!context.schemaVersion||!context.qualityReportHash||context.missingness==null))throw new Error('validation requires schema, quality report, and missingness');if(to==='analyzed'&&(!context.metricVersion||!context.reproducibilityHash||!context.uncertaintyMethod||!context.suppressionApplied))throw new Error('analysis requires definition version, reproducibility, uncertainty, and suppression');if(to==='approved'&&(role!=='qualified_reviewer'||!context.reviewerQualification||!context.interpretation||String(context.preparerId)===String(context.reviewerId)))throw new Error('independent qualified review and interpretation required');if(to==='intervention_active'&&(!context.ownerId||!context.title||!context.outcomeMetric||!context.baseline||!context.target||!context.reviewDate))throw new Error('intervention requires owner, title, baseline, target, outcome metric, and review date');return true;}
module.exports={normalizeManifest,validateMetricDefinition,suppressSmallCohorts,wilsonInterval,analysisHash,assertTransition};
